### ISSUE TITLE
Github won't allow me to commit

### ISSUE THREAD

**Issue by Omcgarry** [dataanalysis3/datan3_2019#4]
![issue](https://user-images.githubusercontent.com/46788925/51913842-6159fa80-23cf-11e9-84d8-dc58ee28c47e.png)

**Comment by abessudnov** [comment]
The reason is that your local version of the files is behind the one you have on Github. You should always start with pressing the "Pull" button in R Studio before you start changing files, to make sure you work with the latest version. Then you will never have this problem. If you want more help I'm happy to explain this in the office hour or feel free to ask Max.
