### ISSUE TITLE
Different Rmd and md outputs

### ISSUE THREAD

**Issue by twgg201** [dataanalysis3/datan3_2019#6]
When I knit my Rmd file, the output for my stable2 data frame on recoding ethnicity to white/non-white is different in the Rmd file (correctly shows values in data frame) to the md file (race and racel_dv are only showing as a series of NA values). This then subsequently displays NA values for all following code, which uses race and racel_dv, meaning that my following data frames do not display correctly in the md file. Is this ok, as my original Rmd file outputs correctly and there are no errors in the code?

**Comment by abessudnov** [comment]
Everything in your md file must show correctly; this is the file I’ll mark. If recode() causes you problems feel free to change the starter code accordingly so that the output is correct. recode() will create missing values when you recode data into a different type and do not provide all the new values explicitly.
